### ISSUE TITLE
Style customization would be a nice addition!

### ISSUE THREAD

**Issue by shaddyhm** [g00fy-/angular-datepicker#287]
Gradients are old... a clear option to change color would be nice.

**Comment by brunokrebs** [comment]
@shaddyhm, there are 112 open issues  as I'm writing this answer. Since there is an easy way to change this component's style, I wouldn't expect any support on this matter.

So, to give you some help, take a look at the following example rule:

``` css
[date-picker] table {
    background-color: #eee;
    border-radius: 3px;
    width: 100%;
}
```

This is how you proceed to style this component. In this case, I have changed the background color, set a different radius to its borders and also forced it to be 100% width.
